### ISSUE TITLE
Need Mac app signing

### ISSUE THREAD

**Issue by theshillito** [very-scary-scenario/business#1]
![screen shot 2017-05-19 at 20 33 02](https://cloud.githubusercontent.com/assets/1828418/26263905/8b0012b0-3cd2-11e7-8e8b-45fc29ca4064.png)

**Comment by colons** [comment]
i'm not going to shell out a hundred bucks a year so that we can distribute a game nobody will play

perhaps in future, if we want to distribute an ios app or something, we can look into this, but for now im okay with people right click » opening
